#!/bin/bash

export GNUPLOT_DEFAULT_GDFONT=inconsolata

job=$(realpath "$1")
confuga=$(realpath "$2")

data=$(mktemp)

sqlite3 -separator $'\t' > "$data"  <<EOF
ATTACH 'file://${job}?mode=ro' as Job;
ATTACH 'file://${confuga}?mode=ro' as Confuga;

SELECT TransferJob.id, TransferJob.time_commit, File.size/(MAX(TransferJob.time_complete-TransferJob.time_commit, 1))
	FROM Confuga.TransferJob JOIN Confuga.File ON TransferJob.fid = File.id
UNION ALL
SELECT TransferJob.id, TransferJob.time_complete, -File.size/(MAX(TransferJob.time_complete-TransferJob.time_commit, 1))
	FROM Confuga.TransferJob JOIN Confuga.File ON TransferJob.fid = File.id;
EOF

gnuplot <<EOF
set terminal svg
set output 'aggregate.svg'

set xdata time
set timefmt "%s"
set format x "%H:%M"
set xlabel "time (minutes)"

set ylabel "aggregate transfer (bytes/s)"
set format y "%0.1e"

plot [][0:] "${data}" using 2:3 title "Aggregate Transfer" smooth cumulative
EOF

# vim: set noexpandtab tabstop=4:
