#!/bin/bash

export GNUPLOT_DEFAULT_GDFONT=inconsolata

job=$(realpath "$1")
confuga=$(realpath "$2")

data=$(mktemp)

echo $0
sqlite3 -separator $'\t' > "$data"  <<EOF
ATTACH 'file://${job}?mode=ro' as Job;
ATTACH 'file://${confuga}?mode=ro' as Confuga;

SELECT id, time_commit, 1
	FROM Confuga.TransferJob
UNION ALL
SELECT id, time_complete+1 /* prevent time_commit == time_complete */, -1
	FROM Confuga.TransferJob;
EOF
cat "$data"

gnuplot <<EOF
set terminal svg
set output 'concurrent-transfers.svg'

set xdata time
set timefmt "%s"
set format x "%H:%M"
set xlabel "time (minutes)"

set ylabel "concurrent transfer jobs"
set mytics

plot [][0:] "${data}" using 2:3 title "Concurrent Transfer Jobs" smooth cumulative
EOF

# vim: set noexpandtab tabstop=4:
