#!/bin/bash

#ARCHIVE=/afs/crc.nd.edu/group/ccl/data/workflows/archives/patrick_bwa.tar.gz

if [ "$(whoami)" = pdonnel3 ]; then
	PORT=9123
elif [ "$(whoami)" = nhazekam ]; then
	PORT=9223
else
	PORT=9523
fi

INSTALL_BASE="$(dirname "$0")"
CHIRP_SERVER="${INSTALL_BASE}/chirp_server"
CHIRP="${INSTALL_BASE}/chirp"
MAKEFLOW="${INSTALL_BASE}/makeflow"

PYTHON="/afs/nd.edu/user37/ccl/software/external/python/bin/python"
WEAVER="$(which weaver)"

DIR="$(pwd)/load-balance.workflow"
MAKEFLOW_FILE="$DIR"/Makeflow

if ! [ -d "$DIR/" ]; then
	mkdir "$DIR"
	(cd "$DIR" && "$PYTHON" "$WEAVER" "${INSTALL_BASE}/load-balance.py")
fi

run () {
	echo "$@"
	time "$@"
}

runbg () {
	echo "$@" '&'
	"$@" &
}

#if ! [ -d "$DIR/" ]; then
#	run tar xzf "$ARCHIVE"
#fi

"${INSTALL_BASE}/ssh-chirps"
sleep 5

for concurrency in 20 16 12 08 04 02 01; do
	for scheduler in fifo-1 fifo-2; do
		for replication in push-sync-1 push-async-2; do
			if [ "$replication" = 'push-sync-1' -a ! \( "$scheduler" = 'fifo-1' \) ]; then
				continue;
			fi
			base="$(pwd)/test.${concurrency}.${scheduler}.${replication}"
			mkdir "$base" || exit 1

			runbg "$CHIRP_SERVER" --auth=unix --catalog-update=30s --debug=all --debug-file="${base}/confuga.debug" --debug-rotate-max=0 --interface=127.0.0.1 --jobs --job-concurrency="$concurrency" --pid-file="${base}/confuga.pid" --port="$PORT" --root="confuga://${base}/confuga.root?scheduler=${scheduler}&replication=${replication}" --superuser="unix:$(whoami)" --transient="${base}/confuga.transient"

			run "$CHIRP" --auth=unix --debug=chirp --debug-file="${base}/chirp.debug" --timeout=20m localhost:"$PORT" put "$DIR/"

			run cp "$MAKEFLOW_FILE" "${base}/Makeflow"
			run "$MAKEFLOW" --batch-type=chirp --debug=all --debug-file="${base}/makeflow.debug" --debug-rotate-max=0 --working-dir="chirp://localhost:${PORT}/$(basename "$DIR")" "${base}/Makeflow"

			kill %1
			wait
			sleep 10
		done
	done
done

# vim: set noexpandtab tabstop=4:
