#!/bin/bash

CHIRP_SERVER="$(dirname "$0")/chirp_server"
USERNAME=$(whoami)

if [ "$(whoami)" = pdonnel3 ]; then
	PORT=9122
elif [ "$(whoami)" = nhazekam ]; then
	PORT=9222
else
	PORT=9522
fi


# This one probably doesn't need changed...
RENDEZVOUS=/afs/crc.nd.edu/user/p/pdonnel3/rendezvous/

CONFUGA_NODE_LIST=""
for i in 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24; do
    BASE="/disk/d10/${USERNAME}"
    CONFUGA_NODE_LIST="${CONFUGA_NODE_LIST},chirp://disc${i}.crc.nd.edu:${PORT}/${BASE}"
    ssh -o PreferredAuthentications=publickey "${USERNAME}@disc${i}.crc.nd.edu" "killall -u ${USERNAME} chirp_server"
    screen -t disc${i}.crc.nd.edu ssh -o PreferredAuthentications=publickey "${USERNAME}@disc$i.crc.nd.edu" "/bin/sh -c '"'BASE='"$BASE"'; rm -rf "$BASE"; mkdir -p "$BASE"; '"$CHIRP_SERVER"' --parent-death --auth=hostname --auth=unix --auth=ticket --challenge-dir='"$RENDEZVOUS"' --transient="$BASE"/chirp.transient --root="$BASE"/chirp.root --port='"$PORT"' --catalog-update=10s --debug=all --debug-file=:stdout --debug-rotate-max=0 --jobs --job-concurrency=100'"'"
done
