#!/bin/bash

export GNUPLOT_DEFAULT_GDFONT=inconsolata

job=$(realpath "$1")
confuga=$(realpath "$2")

data_run=$(mktemp)
data_rec=$(mktemp)
data_sen=$(mktemp)

echo $0
{
	sqlite3 -separator $'\t' | awk '$1 != prev {printf "\n"; prev = $1}; {print}' > "$data_run"
} <<EOF
ATTACH 'file://${job}?mode=ro' as Job;
ATTACH 'file://${confuga}?mode=ro' as Confuga;

CREATE TEMPORARY TABLE IDS AS
	SELECT DISTINCT tag FROM Confuga.TransferJob;

SELECT ConfugaJob.sid, Job.Job.time_start, Job.Job.time_finish, Job.Job.tag, IDS.rowid
	FROM
		Job.Job
		JOIN Job.ConfugaJob ON Job.ConfugaJob.id = Job.id
		JOIN IDS ON Job.Job.tag = IDS.tag;
EOF

{
	sqlite3 -separator $'\t' | awk '$1 != prev {printf "\n"; prev = $1}; {print}' > "$data_rec"
} <<EOF
ATTACH 'file://${confuga}?mode=ro' as Confuga;

CREATE TEMPORARY TABLE IDS AS
	SELECT DISTINCT tag FROM Confuga.TransferJob;

SELECT TransferJob.tsid, TransferJob.time_new, TransferJob.time_complete, Confuga.TransferJob.tag, IDS.rowid
	FROM
		Confuga.TransferJob 
		JOIN IDS ON Confuga.TransferJob.tag = IDS.tag;
EOF

{
	sqlite3 -separator $'\t' | awk '$1 != prev {printf "\n"; prev = $1}; {print}' > "$data_sen"
} <<EOF
ATTACH 'file://${confuga}?mode=ro' as Confuga;

CREATE TEMPORARY TABLE IDS AS
	SELECT DISTINCT tag FROM Confuga.TransferJob;

SELECT TransferJob.fsid, TransferJob.time_new, TransferJob.time_complete, Confuga.TransferJob.tag, IDS.rowid
	FROM
		Confuga.TransferJob 
		JOIN IDS ON Confuga.TransferJob.tag = IDS.tag;
EOF

gnuplot <<EOF
set terminal postscript eps mono
set output 'workspan.eps'

set format x "%H:%M"
set offset graph 0.05, 0.05, 0, 0
set style arrow 1 head filled size screen 0.025,30,45 ls 1
set style line 1 lt 1 lw 8 lc palette z
set style arrow 2 nohead ls 1
set style arrow 3 head ls 1
set style arrow 4 backhead ls 1
set style arrow 5 heads ls 1
set style line 2 lt 1 lw 12 lc palette z
set style arrow 6 nohead ls 2
set palette defined ( 1 "red", 2 "green", 3 "blue", 4 "black")
set timefmt "%s"
set title "Job Heat-Map"
set xdata time
set xlabel "Time (HH:MM)"
set xrange ["00:00":]
set xtics rotate by -45
set ylabel "Storage Node"
set ytics 1,1
set yrange [0:20]
unset colorbox

first=0;
offset=0;
func(x)=(offset=(first==0)?x:offset,first=1,x-offset)

plot "$data_run" u (func(\$2)):(\$1+.2):(func(\$3)-func(\$2)):(0):5 with vectors arrowstyle 2 notitle, \\
 "$data_sen" u (func(\$2)):(\$1+.5):(func(\$3)-func(\$2)):(0):5 with vectors arrowstyle 2 notitle, \\
 "$data_rec" u (func(\$2)):(\$1+.825):(func(\$3)-func(\$2)):(0):5 with vectors arrowstyle 2 notitle, \\
 "$data_run" u (func(\$3)):(\$1+.2):(3):(0):(4) with vectors arrowstyle 6 notitle, \\
 "$data_run" u (func(\$2)):(\$1+.2):(3):(0):(4) with vectors arrowstyle 6 notitle, \\
 for [i=1:20] i notitle ls 3 
EOF

# vim: set noexpandtab tabstop=4:
